apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
  - name: wordpress
    port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress_image
        imagePullPolicy: Never
        name: wordpress
        ports:
        - containerPort: 5050