apiVersion: v1
kind: Service
metadata:
  labels:
    app: ftps
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
  - name: ftps
    port: 21
    protocol: TCP
    targetPort: 21
  - name: ftps-pasv
    port: 30021
    protocol: TCP
    targetPort: 30021
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ftps
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps_image
        imagePullPolicy: Never
        name: ftps
        ports:
        - containerPort: 21
        - containerPort: 30021